package main

import (
	"crypto/md5"
	"fmt"
	"strings"
	"testing"
)

func TestParseDigestMatchesFreshSecret(t *testing.T) {
	wire := `SIP/2.0 407 Proxy Authentication Required
Proxy-Authenticate: Digest realm="96678.falepaco.com.br", nonce="nonce", algorithm=MD5, qop="auth"
SIP/2.0 403 Forbidden
Proxy-Authorization: Digest username="100", realm="96678.falepaco.com.br", nonce="nonce", uri="sip:+5567981340687@96678.falepaco.com.br:5060;transport=tcp", response="", algorithm=MD5, cnonce="cnonce", qop=auth, nc=00000001`
	// The helper is exercised with a response generated by the canonical SIP verifier.
	response := md5hex(md5hex("100:96678.falepaco.com.br:runtime-secret") + ":nonce:00000001:cnonce:auth:" + md5hex("INVITE:sip:+5567981340687@96678.falepaco.com.br:5060;transport=tcp"))
	wire = strings.Replace(wire, `response=""`, `response="`+response+`"`, 1)
	challenge, auth, ok, status := parseDigest(wire, "runtime-secret")
	if !challenge || !auth || !ok || status != 403 {
		t.Fatalf("unexpected digest parse: challenge=%v auth=%v ok=%v status=%d", challenge, auth, ok, status)
	}
}

func md5hex(s string) string { return fmt.Sprintf("%x", md5.Sum([]byte(s))) }
